#!/bin/bash

thisDir=$(pwd)

echo "Updating your current Artix-Runit install to the latest packages."
sudo pacman -Syu

echo "Installing a few dependancies."
sudo pacman -S lua feh neofetch alacritty

echo "Creating $HOME/.mizOS"
if [ -d "$HOME/.mizOS" ]; then
	echo "already made"
else
	mkdir $HOME/.mizOS
fi


echo "Creating $HOME/.mizOS/wallpaper"
if [ -d "$HOME/.mizOS/wallpaper" ]; then
	rm -rf $HOME/.mizOS/wallpaper
else
	mkdir $HOME/.mizOS/wallpaper
fi


echo "creating $HOME/.mizOS/src"
mkdir $HOME/.mizOS/src


echo "Adding that amazing wallpaper to /etc/mizOS/wallpaper"
cp assets/mizOStree.png $HOME/.mizOS/wallpaper

if [ -d "$HOME/.mizOS/yay-git" ]; then
	echo "yay build files found, removing"
	rm -rf $HOME/.mizOS/yay-git
fi

echo "Installing yay, so you dont have to."
cd $HOME/.mizOS
git clone https://aur.archlinux.org/yay-git.git
cd $HOME/.mizOS/yay-git
makepkg -si

cd $thisDir

if [ -d "$HOME/.config/i3" ]; then
	echo "You already have an i3 config folder, were backing that up to HOME/.config/youri3backup."
	mkdir $HOME/.config/youri3backup
	mv $HOME/.config/i3/ $HOME/.config/youri3backup
	mkdir $HOME/.config/i3
	cp assets/i3/config $HOME/.config/i3
else 
	echo "i3-gaps is not installed on this system, were fixing that."
	sudo pacman -S i3-gaps dmenu xclip maim
	cp assets/i3/config $HOME/.config/i3
fi

if test -f "$HOME/.config/picom.conf"; then
	echo "You already have a picom config file, were backing that up to HOME/.config/yourpicombackup."
	mkdir $HOME/.config/yourpicombackup
	mv $HOME/.config/picom.conf $HOME/.config/yourpicombackup
	cp assets/picom.conf $HOME/.config
else
	echo "Picom doesnt seem to be installed, fixing that now."
	sudo pacman -S picom
	cp assets/picom.conf $HOME/.config
fi

if [ -d "$HOME/.config/alacritty" ]; then
	echo "alacritty config folder found. Backing it up to $HOME/.config/youralacrittybackup"
	mkdir $HOME/.config/youralacrittybackup
	mv $HOME/.config/alacritty $HOME/.config/youralacrittybackup
else
	echo "alacritty config folder not found, creating one"
	mkdir $HOME/.config/alacritty
fi

echo "Installing alacritty catppuccin theme"
cp assets/alacritty.yml $HOME/.config/alacritty

echo "Installing the miz script. finally!! :D"

chmod +x assets/miz
sudo cp assets/miz /usr/bin


echo "Changing your os-release file."
sudo rm /etc/os-release
sudo cp assets/os-release /etc

echo "Changing your lsb-release file."
sudo rm /etc/lsb-release
sudo cp assets/lsb-release /etc


echo "My work here is done! You should probably reboot."
echo "  "

echo "If you are currently using i3-gaps, reload with MOD+shift+c, then press MOD+shift+n then MOD+shift+m to see theming changes."
echo " "
echo "! WARNING ! PLEASE REFRAIN FROM USING sudo pacman -Syu to update, instead, PLEASE use miz system update"
