#!/bin/bash

thisDir=$(pwd)

mkdir $HOME/.config

echo "Updating your current install to the latest packages."
sudo -S pacman -Syu

echo "Installing a few dependencies."
sudo -S pacman -S lua feh alacritty asusctl supergfxctl steam firefox neovim

echo "Enabling asusctl and supergfxctl."
sudo -S systemctl enable --now power-profiles-daemon.service
sudo -S systemctl enable --now supergfxd

echo "Creating $HOME/.mizOS"
if [ -d "$HOME/.mizOS" ]; then
	echo "already made"
else
	mkdir $HOME/.mizOS
fi


echo "Creating $HOME/.mizOS/wallpaper"
if [ -d "$HOME/.mizOS/wallpaper" ]; then
	rm -rf $HOME/.mizOS/wallpaper
	mkdir $HOME/.mizOS/wallpaper
else
	mkdir $HOME/.mizOS/wallpaper
fi


echo "creating $HOME/.mizOS/src"
mkdir $HOME/.mizOS/src



echo "Installing custom neofetch."
echo "Uninstalling normal neofetch, if it exists."
sudo -S pacman -S neofetch
sudo -S pacman -R neofetch

if test -f "/usr/bin/neofetch"; then
	echo "Custom neofetch already installed, removing."
fi

sudo -S rm /usr/bin/neofetch
echo "Adding custom neofetch."
sudo -S cp assets/neofetch /usr/bin

echo "Adding that amazing wallpaper to $HOME/.mizOS/wallpaper."
cp assets/mizOStree.png $HOME/.mizOS/wallpaper/

if [ -d "$HOME/.mizOS/yay-git" ]; then
	echo "yay build files found, removing"
	rm -rf $HOME/.mizOS/yay-git
fi

echo "Detecting init."
mkdir $HOME/.mizOS/init
if test -f "/usr/bin/sv"; then
	echo "Runit detected"
	touch $HOME/.mizOS/init/runit
elif test -f "/usr/bin/systemctl"; then
	echo "SystemD detected"
	touch $HOME/.mizOS/init/systemd
elif test -f "/usr/bin/rc-service"; then
	echo "openRC detected"
	touch $HOME/.mizOS/init/openrc
fi







cd $thisDir

if [ -d "$HOME/.config/i3" ]; then
	echo "You already have an i3 config folder, were backing that up to HOME/.config/youri3backup."
	mkdir $HOME/.config/youri3backup
	mv $HOME/.config/i3/ $HOME/.config/youri3backup
	mkdir $HOME/.config/i3
	cp assets/i3/config $HOME/.config/i3/
else 
	echo "i3-gaps is not installed on this system, were fixing that."
	sudo -S pacman -S i3-gaps i3status dmenu xclip maim
	rm -rf $HOME/.config/i3
	mkdir $HOME/.config/i3
	cp assets/i3/config $HOME/.config/i3/
fi

if test -f "$HOME/.config/picom.conf"; then
	echo "You already have a picom config file, were backing that up to HOME/.config/yourpicombackup."
	mkdir $HOME/.config/yourpicombackup
	mv $HOME/.config/picom.conf $HOME/.config/yourpicombackup
	cp assets/picom.conf $HOME/.config
else
	echo "Picom doesnt seem to be installed, fixing that now."
	sudo -S pacman -S picom
	rm $HOME/.config/picom.conf
	cp assets/picom.conf $HOME/.config
fi

if [ -d "$HOME/.config/alacritty" ]; then
	echo "alacritty config folder found. Backing it up to $HOME/.config/youralacrittybackup"
	mkdir $HOME/.config/youralacrittybackup
	mv $HOME/.config/alacritty $HOME/.config/youralacrittybackup
else
	echo "alacritty config folder not found, creating one"
fi
mkdir $HOME/.config/alacritty
echo "Installing alacritty catppuccin theme"
cp assets/alacritty.yml $HOME/.config/alacritty/

echo "Installing the miz script. finally!! :D"

chmod +x assets/miz
sudo -S cp assets/miz /usr/bin


echo "Changing your os-release file."
sudo -S rm /etc/os-release
sudo -S cp assets/os-release /etc

echo "Changing your lsb-release file."
sudo -S rm /etc/lsb-release
sudo -S cp assets/lsb-release /etc


echo "My work here is done! You should probably reboot."
echo "  "

echo "If you are currently using i3-gaps, reload with MOD+shift+c, then press MOD+shift+n then MOD+shift+m to see theming changes."
echo " "
echo "! WARNING ! PLEASE REFRAIN FROM USING sudo pacman -Syu to update, instead, PLEASE use miz update"
