local Data = {}


Data.homeDir = os.getenv("HOME")

Data.initSystem = dofile("/var/mizOS/init/init.lua")

Data.integerCharacterSheet = "0123456789"

Data.hexCharacterSheet = "0123456789abcdef"

Data.UITable = {
        {"budgie", "budgie-desktop", false},
        {"cinnamon", "cinnamon", false},
        {"cutefish", "cutefish", false},
        {"deepin", "deepin", false},
        {"enlightenment", "enlightenment", false},
        {"gnome", "gnome", false},
        {"gnome-flashback", "gnome-flashback", false},
        {"kde", "plasma", false},
        {"lxde", "lxde", false},
        {"lxqt", "lxqt", false},
        {"mate", "mate", false},
        {"sugar", "sugar sugar-fructose", false},
        {"ukui", "ukui", false},
        {"xfce", "xfce4", false},
        {"cde", "cdesktopenv", true},
        {"ede", "ede", true},
        {"kde1", "kde1-kdebase-git", true},
        {"liri", "liri-shell-git", true},
        {"lumina", "lumina-desktop", true},
        {"moksha", "moksha-git", true},
        {"pantheon", "pantheon-session-git", true},
        {"paperde", "paperde", true},
        {"phosh", "phosh", true},
        {"plasma-mobile", "plasma-mobile", true},
        {"thedesk", "thedesk", true},
        {"trinity", "trinity", false},
        {"maui", "maui-shell-git", true},
        {"2bwm", "2bwm", true},
        {"9wm", "9wm", true},
        {"afterstep", "afterstep-git", true},
        {"berry", "berry-git", true},
        {"blackbox", "blackbox", false},
        {"compiz", "compiz", false},
        {"cwm", "cwm", true},
        {"eggwm", "eggwm", true},
        {"evilwm", "evilwm", true},
        {"fluxbox", "fluxbox", false},
        {"flwm", "flwm", true},
        {"fvmm", "fvmm", true},
        {"gala", "gala", false},
        {"goomwwm", "goomwwm", true},
        {"icewm", "icewm", false},
        {"jbwm", "jbwm", true},
        {"jwm", "jwm", false},
        {"karmen", "karmen", true},
        {"kwin", "kwin", false},
        {"lwm", "lwm", false},
        {"marco", "marco", false},
        {"metacity", "metacity", false},
        {"muffin", "muffin", false},
        {"mutter", "mutter", false},
        {"mwm", "openmotif", false},
        {"openbox", "openbox", false},
        {"pawm", "pawm", true},
        {"pekwm", "pekwm", false},
        {"sawfish", "sawfish", true},
        {"sowm", "sowm", true},
        {"tinywm", "tinywm", true},
        {"twm", "xorg-twm", false},
        {"ukwm", "ukwm", false},
        {"uwm", "ude", true},
        {"wind", "windwm", true},
        {"windowlab", "windowlab", true},
        {"windowmaker", "windowmaker", true},
        {"wm2", "wm2", true},
        {"worm", "worm-git", true},
        {"xfwm", "xfwm4", false},
        {"bspwm", "bspwm", false},
        {"exwm", "exwm-git", true},
        {"herbstluftwm", "herbstluftwm", false},
        {"i3", "i3-wm", false},
        {"larswm", "larswm", true},
        {"leftwm", "leftwm", true},
        {"notion", "notion", false},
        {"ratpoison", "ratpoison", false},
        {"stumpwm", "stumpwm", false},
        {"subtle", "subtle-hg", true},
        {"wmfs2", "wmfs2-git", true},
        {"awesome", "awesome", false},
        {"dwm", "dwm", true},
        {"echinus", "echinus", true},
        {"frankenwm", "frankenwm", true},
        {"i3-gaps", "i3-gaps", false},
        {"spectrwm", "spectrwm", false},
        {"sway", "sway", false},
        {"qtile", "qtile", false},
        {"xmonad", "xmonad", false},
        {"hyprland", "hyprland", true}
}



return Data
