#!/bin/lua
-- [ Made by the Duat. https://entertheduat.org ] --

local argCount = #arg

--[=[ Backend setup ]=]--
local NileRiver = dofile("/NileRiver/core/NileRiver.lua")


-- [ Input/Output setup. ] --
local frontend_IO = {}

frontend_IO.inp = function() -- Get user input.
	io.write("\x1b[38;2;137;180;250m> \x1b[38;2;180;190;254m")
	local text = io.read()
	io.write("\x1b[38;2;255;255;255m")
	return text
end
frontend_IO.outp = function(text) -- Write raw output.
	io.write(text)
end
frontend_IO.foutp = function(text) -- Print stylized output.
	print("\x1b[38;2;137;180;250m| \x1b[38;2;180;190;254m" .. text .. "\x1b[38;2;255;255;255m")
end
frontend_IO.afoutp = function(text) -- Print secondary stylized output.
	print("    \x1b[38;2;245;194;231m> \x1b[38;2;203;166;247m" .. text .. "\x1b[38;2;255;255;255m")
end
frontend_IO.err = function(text) -- Print error output.
	print("\x1b[38;2;243;139;168m!![Error]> \x1b[38;2;203;160;247m" .. text .. "\x1b[38;2;255;255;255m")
end

NileRiver.InitializeIO(frontend_IO)


--[=[ Main function handler ]=]--
local function sendInfo()
	NileRiver.Main.Info(arg[2])
end

local function sendConfig()
	NileRiver.Main.Config(arg[2], arg[3])
end

local function sendTheme()
	if arg[2] then
		NileRiver.Main.Theme(arg[2])
	end
end

local function sendService()
	NileRiver.Main.Service(arg[2], arg[3])
end

local function sendGraphics()
	local value
	if arg[2] == "xd" or arg[2] == "xi" then
		value = {}
		local i = 3
		while i <= argCount do
			table.insert(value, arg[i])
			i = i + 1
		end
	else
		value = arg[3]
	end
	NileRiver.Main.Graphics(arg[2], value)
end

local function sendNetwork()
	if arg[3] then
		NileRiver.Main.Network(arg[2], arg[3])
	else
		NileRiver.Main.Network(arg[2], nil)
	end
end

local function sendPkgManager()
	local operator = ""
	local hasRequestedToUseAUR = false
	local packageList = {}

	if arg[1] ==  "fetch" then
		operator = "install"
	else
		operator = arg[1]
	end

	while argCount > 1 do
		if arg[argCount] ~= "-aur" then
			table.insert(packageList, arg[argCount])
		else
			hasRequestedToUseAUR = true
		end
		argCount = argCount - 1
	end

	NileRiver.Main.Pm(operator, packageList, hasRequestedToUseAUR)
end

local function sendUpdate()
	local dev = false
	if arg[2] == "dev" then
		dev = true
	end
	NileRiver.Main.Update("system", dev)
	NileRiver.Main.Update("packages", dev)
end



--[=[ Command processor ]=]--
local firstArgSheet = {
	["info"]    = sendInfo,
	["config"]  = sendConfig,
	["theme"]   = sendTheme,
	["sv"]      = sendService,
	["gfx"]     = sendGraphics,
	["net"]     = sendNetwork,
	["fetch"]   = sendPm,
	["remove"]  = sendPkgManager,
	["update"]  = sendUpdate,
	["start"]   = NileRiver.Main.start -- Takes no arguments.
}

if firstArgSheet[arg[1]] then
	firstArgSheet[arg[1]]()
else
	frontend_IO.err(arg[1] .. " is not a valid river command.")
end
