#!/bin/bash

echo -e "\nInstalling core NILE components."
echo "| Installing init system identification files."
if [ "$1" == "runit" ]; then
        echo "  > Runit detected."
        cp assets/premade_folders/init/runit/init.lua /NileRiver/init
elif [ "$1" == "systemd" ]; then
        echo "  > SystemD detected."
        cp assets/premade_folders/init/systemd/init.lua /NileRiver/init
elif [ "$1" == "openrc" ]; then
        echo "  > OpenRC detected."
        cp assets/premade_folders/init/openrc/init.lua /NileRiver/init
fi
echo "| Installing package manager identification files."
cp assets/premade_folders/pkgmanager/$2/pm.lua /NileRiver/pkgmanager

echo "| Installing core NILE system software."
echo "  > Installing the NileRiver.lua backend."
if [ -f "/NileRiver/core/NileRiver.lua" ]; then
	rm /NileRiver/core/NileRiver.lua
fi
cp assets/premade_folders/core/NileRiver.lua /NileRiver/core/
echo "  > Installing NILE system libraries."
if [ -d "/NileRiver/core/libraries" ]; then
	rm -rf /NileRiver/core/libraries
fi
cp -r assets/premade_folders/core/libraries /NileRiver/core/
touch /NileRiver/core/xinitrc
echo "exec i3" > /NileRiver/core/xinitrc

echo "  > Installing the river frontend."
if [ -f "/usr/bin/river" ]; then
	rm /usr/bin/river
fi
chmod +x assets/premade_folders/river
cp assets/premade_folders/river /usr/bin