#!/bin/bash

echo -e "\nInstalling core NILE components."
echo "| Installing init system identification files."
if [ "$1" == "runit" ]; then
        echo "  > Runit detected."
        cp assets/premade_folders/init/runit/init.lua /NileRiver/init
elif [ "$1" == "systemd" ]; then
        echo "  > SystemD detected."
        cp assets/premade_folders/init/systemd/init.lua /NileRiver/init
elif [ "$1" == "openrc" ]; then
        echo "  > OpenRC detected."
        cp assets/premade_folders/init/openrc/init.lua /NileRiver/init
fi
echo "| Installing package manager identification files."
cp assets/premade_folders/pkgmanager/$2/pm.lua /NileRiver/pkgmanager

echo "| Installing NILE core."
cp -r assets/premade_folders/core/* /NileRiver/core/

echo "  > Installing the river frontend."
if [ -f "/usr/bin/river" ]; then
	rm /usr/bin/river
fi
cp assets/premade_folders/river /usr/bin
chown root:root /usr/bin/river
chmod 755 /usr/bin/river