#!/bin/lua
-- [ Made by the Duat. https://entertheduat.org ] --

local argCount = #args

--[=[ Backend setup ]=]--
local mizOS = dofile("/var/mizOS/core/mizOS.lua")


-- [ Input/Output setup. ] --
local frontend_IO = {}

frontend_IO.inp = function() -- Get user input.
	return read()
end
frontend_IO.outp = function(text) -- Write raw output.
	io.write(text)
end
frontend_IO.foutp = function(text) -- Print stylized output.
	print("\x1b[38;2;137;180;250m| \x1b[38;2;180;190;254m" .. text .. "\x1b[38;2;255;255;255m")
end
frontend_IO.afoutp = function(text) -- Print alternate stylized output.
	print("    \x1b[38;2;245;194;231m> \x1b[38;2;203;166;247m" .. text .. "\x1b[38;2;255;255;255m")
end
frontend_IO.err = function(text) -- Print error output.
	print("\x1b[38;2;243;139;168m!![Error]> \x1b[38;2;203;160;247m" .. text .. "\x1b[38;2;255;255;255m")
end

mizOS.initializeIO(frontend_IO)


--[=[ System function handler ]=]--
local function sendInfo()
	mizOS.System.info(args[2])
end

local function sendConfig()
	mizOS.System.config(args[2], args[3])
end

local function sendService()
	mizOS.System.service(args[2], args[3])
end

local function sendGraphics()
	local value
	if args[2] == "xd" or args[2] == "xi" then
		value = {}
		while argCount > 2 do
			table.insert(value, args[argCount])
			argCount = argCount - 1
		end
	else
		value = args[3]
	end
	mizOS.System.graphics(args[2], value)
end

local function sendSoftware()
	if args[2] == "cc" then
		mizOS.System.software("clear cache")
		os.exit()
	end
	local packageList = {}
	while argCount > 2 do
		table.insert(packageList, args[argCount])
		argCount = argCount - 1
	end
	local channelTranslation = {
		["-m"] = "mizos",
		["-p"] = "pacman",
		["-a"] = "aur",
		["-d"] = "desktop"
	}
	mizOS.System.software(args[1], channelTranslation[args[2]], packageList)
end

local function sendUpdate()
	local dev = false
	if args[2] == "dev" then
		dev = true
	end
	mizOS.System.update("system", dev)
	mizOS.System.update("packages", dev)
end


--[=[ Command processor ]=]--
local firstArgSheet = {
	["info"] = sendInfo,
	["config"] = sendConfig,
	["sv"] = sendService,
	["gfx"] = sendGraphics,
	["fetch"] = sendSoftware,
	["remove"] = sendSoftware,
	["cc"] = sendSoftware,
	["update"] = sendUpdate
}

if firstArgSheet[args[1]] then
	firstArgSheet[args[1]]()
else
	frontend_IO.err(args[1] .. "is not a valid \"miz\" command.")
end
