#!/bin/lua



--[=[--[=[ FRONTEND SETUP ]=]--]=]--

-- Load in the backend.
local mizOS = dofile("/var/mizOS/core/mizOS.lua")

-- Frontend to backend package manager channel translation table.
local channels = {
	["-m"] = "mizos",
	["-u"] = "ui",
	["-p"] = "pacman",
	["-a"] = "aur"
}



--[=[--[=[ GENERAL PURPOSE FUNCTIONS ]=]--]=]--

-- Shorten command execution function.
local function x(cmd)
	os.execute(cmd)
end

-- Collects all package names from arguments list.
local function setpkgs(args)
	local pacs = {}
	for _,ag in pairs(args) do
		if ag ~= "fetch"
		and ag ~= "remove"
		and not channels[ag] then
			table.insert(pacs, ag)
		end
	end
	return pacs
end



--[=[--[=[ INPUT/OUTPUT ]=]--]=]--

local function inp()  -- Get user input.
		io.write("\n> ")
		return io.read()
end

local function outp(text)  -- Print raw output.
		io.write(text)
end

local function foutp(text)  -- Print fancy output.
		print("| " .. text)
end

local function afoutp(text)  -- Print alternate fancy output.
		print("    > " .. text)
end

local function err(text)  -- Print error messages.
	print("!!> \x1b[38;2;243;139;168m" .. text .. "\x1b[38;2;255;255;255m")
end

-- Send IO functions to the mizOS backend.
-- the mizOS backend will use these functions for IO.
mizOS.initializeIO(inp, outp, foutp, afoutp, err)



--[=[--[=[ FRONTEND COMMAND FUNCTIONS ]=]--]=]--

-- Service management.
-- (miz sv)
local function sv(args)
mizos.service(args[2], args[3])
		if data then
		process(data)
	end
end

-- Fetch/remove packages 
-- (miz fetch, miz remove)
local function fandr(args)
	local pacs = setpkgs(args)
	mizOS.system.software(args[1], channels[args[2]], pacs)
end

-- Clear cache
-- (miz cc)
local function cc(args)
	mizOS.system.software("clear cache", nil, nil)
end

-- List packages
-- (miz lspkgs)
local function list(args)
	mizOS.system.software("list packages", channels[args[1]], nil)
end

-- GPU management
local function gfx(args)
	local data
	if args[2] == "mode" then
		data = mizos.gfx("mode", args[3], args)
	else
		data = mizos.gfx(args[2], nil, args)
	end
	if data then
		process(data)
	end
end

-- mizOS configuration
local function config(args)
	local data = mizos.config(args[2], args[3])
	if data[1] and data[2] then
		process(data)
	end
end

-- mizOS system updating
local function update(args)
	local dev = false
	if args[2] == "dev" then
		dev = true
	end
	mizos.update("system", dev)
	mizos.update("packages", dev)
end

-- System info
local function info(args)
	local data = mizos.info(args[2])
	if data[1] and data[1] ~= "info" then
		process(data)
	elseif data[1] == "info" then
		if data[2][1] == "desktops" then
			echo("output", "mizOS DE/WM list:")
			for _,desktop in pairs(data[2][2]) do
				local dtype = ""
				if desktop[3] == true then
					dtype = "      (AUR)"
				elseif desktop[3] == false then
					dtype = "      (pacman)"
				end
				print(desktop[1] .. dtype)
			end
		end
	end
end

-- System safety
local function safety(args)
	local data
	if args[3] ~= nil then
		data = mizos.safety(args[2], args[3])
	else
		data = mizos.safety(args[2], nil)
	end
	if data then
		process(data)
	end
end


-- Command proccessor
local basecommands = {
	["sv"] = sv,
	["fetch"] = fandr,
	["remove"] = fandr,
	["cc"] = cc,
	["list"] = list,
	["gfx"] = gfx,
	["config"] = config,
	["update"] = update,
	["info"] = info,
	["backup"] = safety,
	["restore"] = safety
}


local args = {}
for _,v in pairs(arg) do
	if v ~= "/bin/lua" and v ~= "miz" and v ~= "/usr/bin/miz" then
		table.insert(args, v)
	end
end

if basecommands[args[1]] then
	basecommands[args[1]](args)
else
	local command = ""
	for _,cmd in pairs(args) do
		command = command .. cmd .. " "
	end
	mizos.root(command)
end
