#!/bin/lua



--[=[--[=[ FRONTEND SETUP ]=]--]=]--

-- Load in the backend.
local mizOS = dofile("/var/mizOS/core/mizOS.lua")

-- Frontend to backend package manager channel translation table.
local channels = {
	["-m"] = "mizos",
	["-u"] = "ui",
	["-p"] = "pacman",
	["-a"] = "aur"
}



--[=[--[=[ GENERAL PURPOSE FUNCTIONS ]=]--]=]--

-- Shorten command execution function.
local function x(cmd)
	os.execute(cmd)
end

-- Collects all package names from arguments list.
local function setpkgs(args)
	local pacs = {}
	for _,ag in pairs(args) do
		if ag ~= "fetch"
		and ag ~= "remove"
		and not channels[ag] then
			table.insert(pacs, ag)
		end
	end
	return pacs
end



--[=[--[=[ INPUT/OUTPUT ]=]--]=]--

inout = {} -- IO table.
inout.inp = function()  -- Get user input.
		io.write("\n> ")
		return io.read()
end

inout.outp = function(text)  -- Print raw output.
		io.write(text)
end

inout.foutp = function(text)  -- Print fancy output.
		print("| " .. text)
end

inout.afoutp = function(text)  -- Print alternate fancy output.
		print("    > " .. text)
end

inout.err = function(text)  -- Print error messages.
	print("!!> \x1b[38;2;243;139;168m" .. text .. "\x1b[38;2;255;255;255m")
end

-- Send IO functions to the mizOS backend.
-- the mizOS backend will use these functions for IO.
mizOS.initializeIO(inout)



--[=[--[=[ FRONTEND COMMAND FUNCTIONS ]=]--]=]--

-- Service management.
-- (miz sv)
local function sv(args)
    mizOS.system.service(args[2], args[3])  -- System functions are stored in the mizOS.system table.
end

-- Fetch/remove packages.
-- (miz fetch, miz remove)
local function fandr(args)
	local pacs = setpkgs(args)
	mizOS.system.software(args[1], channels[args[2]], pacs)
end

-- Clear cache.
-- (miz cc)
local function cc(args)
	mizOS.system.software("clear cache", nil, nil)
end

-- List packages.
-- (miz lspkgs)
local function list(args)
	mizOS.system.software("list packages", channels[args[1]], nil)
end

-- GPU management.
-- (miz gfx)
local function gfx(args)
	local data
	if args[2] == "mode" then
		mizOS.system.gfx("mode", args[3], args)
	else
		mizOS.system.gfx(args[2], nil, args)
	end
end

-- mizOS configuration.
-- (miz config)
local function config(args)
	mizOS.system.config(args[2], args[3])
end

-- mizOS system updating.
-- (miz update)
local function update(args)
	local dev = false
	if args[2] == "dev" then
		dev = true
	end
	mizOS.system.update("system", dev)
	mizOS.system.update("packages", dev)
end

-- System info.
-- (miz info)
local function info(args)
	mizOS.system.info(args[2])
end

-- System safety.
-- (miz backup, miz restore)
local function safety(args)
	if args[3] ~= nil then
		mizOS.system.safety(args[2], args[3])
	else
		mizOS.system.safety(args[2], nil)
	end
end



--[=[--[=[ COMMAND INTERPRETER ]=]--]=]--

-- Command to function translation table.
local basecommands = {
	["sv"] = sv,
	["fetch"] = fandr,
	["remove"] = fandr,
	["cc"] = cc,
	["list"] = list,
	["gfx"] = gfx,
	["config"] = config,
	["update"] = update,
	["info"] = info,
	["backup"] = safety,
	["restore"] = safety
}

-- Wipe unneeded arguments.
local args = {}
for _,v in pairs(arg) do
	if v ~= "/bin/lua" and v ~= "miz" and v ~= "/usr/bin/miz" then
		table.insert(args, v)
	end
end

-- Check if the first argument exists in the translation table.
if basecommands[args[1]] then
	basecommands[args[1]](args)  -- If it does, run the corresponding function.
else
	local command = ""  -- If it isn't, concatenate arguments into a string, run string as command under root.
	for _,cmd in pairs(args) do
		command = command .. cmd .. " "
	end
	mizOS.system.root(command)
end
