#!/bin/lua

-- Made by https://theduat.neocities.org



local home = os.getenv("HOME")

--[=[ Commonly used functions. ]=]--
local function x(cmd)
	os.execute(cmd)
end

local function ipkg(pkg)
	x("sudo pacman -S " .. pkg)
end

local function ypkg(pkg)
	x("yay -S " .. pkg)
end



---[=[ String split function ]=]--
local function splitstr(ins, sep)
	if sep == nil then
		sep = " "
	end
	local t = {}
	if ins and sep then
		for str in string.gmatch(ins, "([^"..sep.."]+)") do
			table.insert(t, str)
		end
	end
	return t
end



--[=[ Get shell command output. ]=]--
local function capture(cmd, raw)
	local file = assert(io.popen(cmd, 'r'))
	local out = assert(file:read('*a'))
	file:close()
	if raw then return out end
	out = string.gsub(out, '^%s+', '')
	out = string.gsub(out, '%s+$', '')
	out = string.gsub(out, '[\n\r]+', ' ')
	return out
end



--[=[ Check if file exists. ]=]--
local function checkfile(name)
	local file = io.open(name, "r")
        if file ~= nil then
                io.close(file)
 		return true
	end
end



--[=[ https://github.com/Mizosu97/mgpu ]=]--
local function mgpu()
	local gcmd = ""
	for _,ag in pairs(arg) do
		if ag ~= "miz" 
		and ag ~= "/bin/lua" 
		and ag ~= "/usr/bin/miz" 
		and ag ~= "./miz" 
		and ag ~= "d" 
		and ag ~= "i" 
		and ag ~= "gfx" 
		and ag ~= "x" then
			gcmd = gcmd .. ag .. " "
		end
	end
	if arg[3] == "d" then
		x("export DRI_PRIME=1 && exec " .. gcmd)
	elseif arg[3] == "i" then
		x("export DRI_PRIME=0 && exec " .. gcmd)
	end
end



--[=[ Detect init system. ]=]--
local init
if checkfile(home .. "/.mizOS/init/runit") == true then
	init = "runit"
elseif checkfile(home .. "/.mizOS/init/systemd") == true then
	init = "systemd"
elseif checkfile(home .. "/.mizOS/init/openrc") == true then
	init = "openrc"
end



--[=[ Preset list of Desktop Environments and Window Managers. ]=]--
uis = { 
	{"budgie", "budgie-desktop", false},
	{"cinnamon", "cinnamon", false},
	{"cutefish", "cutefish", false},
	{"deepin", "deepin", false},
	{"enlightenment", "enlightenment", false},
	{"gnome", "gnome", false},
	{"gnome-flashback", "gnome-flashback", false},
	{"kde", "plasma", false},
	{"lxde", "lxde", false},
	{"lxqt", "lxqt", false},
	{"mate", "mate", false},
	{"sugar", "sugar sugar-fructose", false},
	{"ukui", "ukui", false},
	{"xfce", "xfce4", false},
	{"cde", "cdesktopenv", true},
	{"ede", "ede", true},
	{"kde1", "kde1-kdebase-git", true},
	{"liri", "liri-shell-git", true},
	{"lumina", "lumina-desktop", true},
	{"moksha", "moksha-git", true},
	{"pantheon", "pantheon-session-git", true},
	{"paperde", "paperde", true},
	{"phosh", "phosh", true},
	{"plasma-mobile", "plasma-mobile", true},
	{"thedesk", "thedesk", true},
	{"trinity", "trinity", false},
	{"maui", "maui-shell-git", true},
	{"2bwm", "2bwm", true},
	{"9wm", "9wm", true},
	{"afterstep", "afterstep-git", true},
	{"berry", "berry-git", true},
	{"blackbox", "blackbox", false},
	{"compiz", "compiz", false},
	{"cwm", "cwm", true},
	{"eggwm", "eggwm", true},
	{"evilwm", "evilwm", true},
	{"fluxbox", "fluxbox", false},
	{"flwm", "flwm", true},
	{"fvmm", "fvmm", true},
	{"gala", "gala", false},
	{"goomwwm", "goomwwm", true},
	{"icewm", "icewm", false},
	{"jbwm", "jbwm", true},
	{"jwm", "jwm", false},
	{"karmen", "karmen", true},
	{"kwin", "kwin", false},
	{"lwm", "lwm", false},
	{"marco", "marco", false},
	{"metacity", "metacity", false},
	{"muffin", "muffin", false},
	{"mutter", "mutter", false},
	{"mwm", "openmotif", false},
	{"openbox", "openbox", false},
	{"pawm", "pawm", true},
	{"pekwm", "pekwm", false},
	{"sawfish", "sawfish", true},
	{"sowm", "sowm", true},
	{"tinywm", "tinywm", true},
	{"twm", "xorg-twm", false},
	{"ukwm", "ukwm", false},
	{"uwm", "ude", true},
	{"wind", "windwm", true},
	{"windowlab", "windowlab", true},
	{"windowmaker", "windowmaker", true},
	{"wm2", "wm2", true},
	{"worm", "worm-git", true},
	{"xfwm", "xfwm4", false},
	{"bspwm", "bspwm", false},
	{"exwm", "exwm-git", true},
	{"herbstluftwm", "herbstluftwm", false},
	{"i3", "i3-wm", false},
	{"larswm", "larswm", true},
	{"leftwm", "leftwm", true},
	{"notion", "notion", false},
	{"ratpoison", "ratpoison", false},
	{"stumpwm", "stumpwm", false},
	{"subtle", "subtle-hg", true},
	{"wmfs2", "wmfs2-git", true},
	{"awesome", "awesome", false},
	{"dwm", "dwm", true},
	{"echinus", "echinus", true},
	{"frankenwm", "frankenwm", true},
	{"i3-gaps", "i3-gaps", false},
	{"spectrwm", "spectrwm", false},
	{"sway", "sway", false},
	{"qtile", "qtile", false},
	{"xmonad", "xmonad", false}
}

local function getuilist()
	print("List of DEs and WMs:")
	print(" ")
	for _,desktop in pairs(uis) do
                local name
                if desktop[3] == false then
                        name = desktop[1] .. "   (pacman)"
                elseif desktop[3] == true then
                        name = desktop[1] .. "   (AUR)"
                end
                print(name)
        end
end



--[=[ Config stuff. ]=]--
conf = {
	{"miz", "/usr/bin/miz", true},
	{"i3", home .. "/.config/i3/config", false},
	{"pacman", "/etc/pacman.conf", true},
	{"xrc", home .. "/.xinitrc", false}
}

local function getconflist()
	print("List of available config files:")
	print(" ")
	for _,confile in pairs(conf) do
		local name
		if checkfile(confile[2]) == true then
			if confile[3] == true then
				name = confile[1] .. "   (Requires root)"
			else
				name = confile[1]
			end
			print(name)
		end
	end
end

local function config()
	for _,confile in pairs(conf) do
		if confile[1] == arg[2] then
			if checkfile(confile[2]) == true then
				if confile[3] == true then
					x("sudo nvim " .. confile[2])
				else
					x("nvim " .. confile[2])
				end
			else
				print("Config file does not exist.")
			end
		end
	end
end



--[=[ mizOS package management. ]=]--
local function package(op, thepkg)
	local pkgsplit
	if thepkg then
		pkgsplit = splitstr(arg[2], "/")
	end
	if op == "install" then
		io.write("\nInstall " .. pkgsplit[2] .. " by " .. pkgsplit[1] .. "? (y/n)\n\n> ")
		if io.read() == "y" then
			x([[su -c "rm -rf $HOME/.mizOS/work/*" root]])
			x("cd $HOME/.mizOS/work && git clone https://github.com/" .. pkgsplit[1] .. "/" .. pkgsplit[2])
			if checkfile(home .. "/.mizOS/work/" .. pkgsplit[2] .. "/MIZOSPKG") == true then				
				local info = dofile(home .. "/.mizOS/work/" .. pkgsplit[2] .. "/info.lua")
				local pacpkgs = ""
				local aurpkgs = ""
				for _,pacdep in pairs(info.pacman_depends) do
					pacpkgs = pacpkgs .. pacdep .. " "
				end
				for _,aurdep in pairs(info.aur_depends) do
					aurpkgs = aurpkgs .. aurdep .. " "
				end
				ipkg(pacpkgs)
				ypkg(aurpkgs)
				x("mkdir $HOME/.mizOS/packages/" .. pkgsplit[1] .. "_" .. pkgsplit[2])
				x("cp $HOME/.mizOS/work/" .. pkgsplit[2] .. "/info.lua $HOME/.mizOS/packages/" .. pkgsplit[1] .. "_" .. pkgsplit[2] .. "/")
				x("cd $HOME/.mizOS/work/" .. pkgsplit[2] .. " && ./install")
			else
				print("[Error] - That package either doesn't exist, or was not made correctly.")
			end
		end
	elseif op == "remove" then
		io.write("\nRemove " .. pkgsplit[2] .. " by " .. pkgsplit[1] .. "? (y/n)\n\n> ")
		if io.read() == "y" then
			if checkfile(home .. "/.mizOS/packages/" .. pkgsplit[1] .. "_" .. pkgsplit[2] .. "/info.lua") == true then
				local info = dofile(home .. "/.mizOS/packages/" .. pkgsplit[1] .. "_" .. pkgsplit[2] .. "/info.lua")
				for _,file in pairs(info.files) do
					x("sudo rm " .. file)
				end
				for _,folder in pairs(info.directories) do
					x("sudo rm -rf " .. folder)
				end
				local pacpkgs = ""
				local aurpkgs = ""
				for _,pacdep in pairs(info.pacman_depends) do
					pacpkgs = pacpkgs .. pacdep .. " "
				end
				for _,aurdep in pairs(info.aur_depends) do
					aurpkgs = aurpkgs .. aurdep .. " "
				end
				print("Pacman dependencies:\n")
				print(pacpkgs)
				print("\n\nAUR dependencies:\n")
				print(aurpkgs)
				io.write("\n\nRemove dependencies for " .. arg[2] .. " ? (y/n)\n\n> ")
				if io.read() == "y" then
					x("sudo pacman -R " .. pacpkgs)
					x("yay -R " .. aurpkgs)
				end
				x("sudo rm -rf $HOME/.mizOS/packages/" .. pkgsplit[1] .. "_" .. pkgsplit[2])
				print(arg[2] .. "has been uninstalled.")
			else
				print("[Error] - That package is not installed.")
			end
		end
	elseif op == "list" then
		x("ls $HOME/.mizOS/packages")
	end
end



--[=[ Software management. ]=]--
local function software()
	local packages = ""
	for _,ag in pairs(arg) do
		if ag ~= "miz" 
		and ag ~= "/bin/lua" 
		and ag ~= "/usr/bin/miz" 
		and ag ~= "./miz"  
		and ag ~= "fetch" 
		and ag ~= "update" 
		and ag ~= "remove" 
		and ag ~= "-p" 
		and ag ~= "-u" 
		and ag ~= "-a" 
		and ag ~= "neofetch" then
			packages = packages .. ag .. " "
		end
	end
	if arg[1] == "fetch" then
		if arg[2] == "-a" then
			ypkg(packages)
		elseif arg[2] == "-c" then
			print("not implemented yet")
		elseif arg[2] == "-u" then
			for _,desktop in pairs(uis) do
                        	if desktop[1] == arg[3] then                                                 
					if desktop[3] == false then
                                        	ipkg(desktop[2])
                                	elseif desktop[3] == true then
                                        	ypkg(desktop[2])                                               
					end
                       		end
                	end
		elseif arg[2] == "-p" then
			x("sudo pacman -S " .. packages)
		else
			package("install", arg[2])
		end
	elseif arg[1] == "remove" then
		if arg[2] == "-a" then
			x("yay -Rn " .. packages)
		elseif arg[2] == "-u" then
			for _,desktop in pairs(uis) do
                                if desktop[1] == arg[3] then  
					if desktop[3] == false then
						x("sudo pacman -Rn " .. desktop[2])
                                        elseif desktop[3] == true then
                                                x("yay -Rn " .. desktop[2])

                                        end
                                end
                        end
		elseif arg[2] == "-p" then
			x("sudo pacman -Rn " .. packages)
		else
			package("remove", arg[2])
		end
	elseif arg[1] == "cc" then
		x("yay -Scc")
		if init == "systemd" then
			x("sudo journalctl --vacuum-time=21days")
		else
			print("SystemD not found, unable to clear journal logs.")
		end
	elseif arg[1] == "lspkgs" then
		package("list", nil)
	else
		print("[sw] > Command not found!")
	end
end



--[=[ Runit command conversion ]=]--
local function runit()
	if arg[2] == "link" then
                        x("sudo ln -s /etc/runit/sv/" .. arg[3] .. " /run/runit/service/")
        elseif arg[2] == "unlink" then   
		x("sudo rm /run/runit/service/" .. arg[3])   
	elseif arg[2] == "disable" then
		x("sudo touch /run/runit/service/" .. arg[3] .. "/down")  
	elseif arg[2] == "enable" then
                x("sudo rm /run/runit/service/" .. arg[3] .. "/down")
        elseif arg[2] == "start" then
                x("sudo sv start " .. arg[3])
        elseif arg[2] == "stop" then         
		x("sudo sv stop " .. arg[3])
        elseif arg[2] == "restart" then
                x("sudo sv restart " .. arg[3])
        elseif arg[2] == "list" then
                if arg[3] == "installed" then   
			x("ls /etc/runit/sv/")
                elseif arg[3] == "linked" then  
			x("ls /run/runit/service/")
                end
	else
		print("[sv_runit] > Command not found!")
        end
end



--[=[ SystemD command conversion. ]=]--
local function systemd()
	if arg[2] == "link" then              
		print("already done")
        elseif arg[2] == "unlink" then
                print("brah??")
        elseif arg[2] == "disable" then
                x("sudo systemctl disable " .. arg[3])
        elseif arg[2] == "enable" then
                x("sudo systemctl enable " .. arg[3])
        elseif arg[2] == "start" then
                x("sudo systemctl start " .. arg[3])
        elseif arg[2] == "stop" then
                x("sudo systemctl stop " .. arg[3])
        elseif arg[2] == "restart" then
                x("sudo systemctl restart " .. arg[3])
        elseif arg[2] == "list" then
                if arg[3] == "installed" then      
			x("systemctl list-units --type=service --all")    
		elseif arg[3] == "linked" then                              
			x("systemctl list-units --state=enabled")
                end
	else
		print("[sv_systemd] > Command not found!")
        end
end



--[=[ OpenRC command conversion ]=]--
local function openrc()
	if arg[2] == "link" then       
		print("already done")
        elseif arg[2] == "unlink" then
                print("brah??")  
	elseif arg[2] == "disable" then  
		x("sudo rc-update del " .. arg[3] .. " default")  
	elseif arg[2] == "enable" then  
		x("sudo rc-update add " .. arg[3] .. " default")  
	elseif arg[2] == "start" then
                x("sudo rc-service " .. arg[3] .. " start")
        elseif arg[2] == "stop" then
                x("sudo rc-service " .. arg[3] .. " stop")
        elseif arg[2] == "restart" then
                x("sudo rc-service " .. arg[3] .. " restart")
        elseif arg[2] == "list" then
                if arg[3] == "installed" then
                        x("rc-update show")
                elseif arg[3] == "linked" then
                        x("rc-update -v show")
                end
	else
		print("[sv_openrc] > Command not found!")
        end
end



--[=[ Service. ]=]--
local function service()
	if init == "runit" then
		runit()
	elseif init == "systemd" then
		systemd()
	elseif init == "openrc" then
		openrc()
	else
		print("Your init system is not supported.")
	end
end



--[=[ Graphics stuff. ]=]--
local function gfx()
	if arg[2] == "x" then
                mgpu()
        elseif arg[2] == "mode" then 
		if arg[3] == "i" then
                        x("supergfxctl --mode integrated")
                elseif arg[3] == "d" then
                        x("supergfxctl --mode dedicated")
                elseif arg[3] == "h" then
                        x("supergfxctl --mode hybrid")
                elseif arg[3] == "c" then  
			x("supergfxctl --mode compute")
                elseif arg[3] == "v" then
                        x("supergfxctl --mode vfio")
                end
	else
		print("[gfx] > Command not found!")
        end
end



--[=[ Info ]=]--
local function info()
	if arg[2] == "help" then
                print(" ")
                print("https://discord.gg/CzHw7cXKCx")
                print(" ")
        elseif arg[2] == "source" then
		prjnt(" ")
                print("https://github.com/Mizosu97/mizOS")
        elseif arg[2] == "creator" then
                print(" ")
                print("https://theduat.neocities.org")
		print(" ")
        elseif arg[2] == "uilist" then
                getuilist()
	elseif arg[2] == "configlist" then
                getconflist()
	else
		x("neofetch")
	end
end



--[=[ System updater. ]=]--
local function update()
	io.write("Update mizOS? y/n \n\n> ")
        if io.read() == "y" then
                x("sudo rm -rf $HOME/.mizOS/src/mizOS")
                x("cd $HOME/.mizOS/src && git clone https://github.com/Mizosu97/mizOS")
                x("sudo rm /usr/bin/miz")
                x("rm -rf $HOME/.config/youri3backup")
                x("rm -rf $HOME/.config/yourpicombackup")
                x("rm -rf $HOME/.config/youralacrittybackup")
                x("cd $HOME/.mizOS/src/mizOS && ./install")
		local updatepkgst = capture("ls $HOME/.mizOS/packages")
		local updatepkgs = splitstr(updatepkgst, " ")
		for _,pkg in pairs(updatepkgs) do
			splitpkg = splitstr(pkg, "_")
			finalpkg = splitpkg[1] .. "/" .. splitpkg[2]
			package("remove", finalpkg)
			package("install", finalpkg)
		end
        end
end



--[=[ Root ]=]--
local function root()
	local cmd = ""
	for _,ag in pairs(arg) do
		if ag ~= "./miz"
		and ag ~= "/bin/lua"
		and ag ~= arg[0] then
			cmd = cmd .. ag .. " "
		end
	end
	local final = [[su -c "]] .. cmd .. [[" root]]
	x(final)
end



--[=[ Core command processor. ]=]--
mizos = {
	["sv"] = service,
	["fetch"] = software,
	["remove"] = software,
	["cc"] = software,
	["lspkgs"] = software,
	["gfx"] = gfx,
	["conf"] = config,
	["update"] = update,
	["info"] = info
}

if mizos[tostring(arg[1])] then
	mizos[arg[1]]()
else
	root()
end
