#!/bin/lua

-- sonic visits ohio
local mizos = dofile("/var/mizOS/core/mizOS.lua")


-- Channel data
local channels = {
	["-m"] = "mizos",
	["-u"] = "ui",
	["-p"] = "pacman",
	["-a"] = "aur"
}


-- Shorten command execution function
local function x(cmd)
	os.execute(cmd)
end

-- Collects all package names
local function setpkgs(args)
	local pacs = ""
	for _,ag in pairs(args) do
		if ag ~= "fetch" and ag ~= "remove" and not channels[ag] then
			pacs = pacs .. ag
		end
	end
	return pacs
end

-- Output coloring/formatting
local function echo(datatype, contents)
	if datatype == "error" then
		print("!!> \x1b[38;2;243;139;168m" .. contents .. "\x1b[38;2;255;255;255m")
	elseif datatype == "output" then
		print("> " .. contents)
	elseif datatype == "rawput" then
		print(contents)
	end
end

-- Get input
local function read(text)
	io.write(text .. "\n\n> ")
	return io.read()
end

-- Process data returned from mizOS backend
local function process(data)
	local datatype = data[1]
	local contents = data[2]
	if datatype == "output" then
		echo(contents, datatype)
	elseif datatype == "error" then
		echo(contents, datatype)
	elseif datatype == "command" then
		x(contents)
	end
end


-- Service management
local function sv(args)
	local data = mizos.service(args[2], args[3])
	if data then
		process(data)
	end
end

-- Fetch/remove packages
local function fandr(args)
	local pacs = setpkgs(args)
	local data = mizos.software(args[1], channels[args[2]], pacs)
	if data then
		process(data)
	end
end

-- Clear cache
local function cc(args)
	local data = mizos.software("clear cache", nil, nil)
	if data then
		process(data)
	end
end

-- List packages
local function list(args)
	local data = mizos.software("list packages", channels[args[1]], nil)
	if data and data[1] ~= "info" then
		process(data)
		elseif data[1] == "info" then
		echo("output", "mizOS package list:")
		for _,pkg in pairs(data[2]) do
			echo("rawput", pkg)
		end
	end 
end

-- GPU management
local function gfx(args)
	local data
	if args[2] == "mode" then
		data = mizos.gfx("mode", args[3], args)
	else
		data = mizos.gfx(args[2], nil, args)
	end
	if data then
		process(data)
	end
end

-- mizOS configuration
local function conf(args)
	print("Currently WIP")
end

-- mizOS system updating
local function update(args)
	mizos.update("system")
	mizos.update("packages")
end

-- System info
local function info(args)
	local data = mizos.info(args[2])
	if data and data[1] ~= "info" then
		process(data)
	elseif data[1] == "info" then
		if data[2][1] == "desktops" then
			echo("output", "mizOS DE/WM list:")
			for _,desktop in pairs(data[2][2]) do
				local dtype = ""
				if desktop[3] == true then
					dtype = "      (AUR)"
				elseif desktop[3] == false then
					dtype = "      (pacman)"
				end
				print(desktop[1] .. dtype)
			end
		end
	end
end



-- Command proccessor
local basecommands = {
	["sv"] = sv,
	["fetch"] = fandr,
	["remove"] = fandr,
	["cc"] = cc,
	["list"] = list,
	["gfx"] = gfx,
	["conf"] = conf,
	["update"] = update,
	["info"] = info
}


local args = {}
for _,v in pairs(arg) do
	if v ~= "/bin/lua" and v ~= "miz" then
		table.insert(args, v)
	end
end

if basecommands[args[1]] then
	basecommands[args[1]](args)
else
	mizos.root(args)
end
