#!/bin/lua

local mizos = dofile("/data/data/com.termux/files/home/mizos/assets/os/testing/mizOS.lua")

local function key()
	os.execute("stty cbreak </dev/tty >/dev/tty 2>&1")
	local key = io.read(1)
	os.execute("stty -cbreak </dev/tty >/dev/tty 2>&1");
	return(key);    
end



local function cmenu(menu)
	os.execute("clear")
	local id = 1
	for _,listing in pairs(menu) do
		local prefix = "\x1b[38;2;255;255;255m"
		local postfix = "\x1b[38;2;255;255;255m"
		if listing["val"] == true then
			prefix = "\x1b[38;2;0;0;255m"
		end
		print(prefix .. listing["name"] .. postfix)
	end
end


local main = {
		[1] = {["name"] = "Service management", ["val"] = true},
		[2] = {["name"] = "Edit repo", ["val"] = false},
		[3] = {["name"] = "Push repo", ["val"] = false}
}





local currentmenu = main



local function move(con)
	local currentdir = 1
	local todir = 0
	local controls = {
		["^[[A"] = "up",
		["^[[B"] = "down"
	}
	
	for _,listing in pairs(currentmenu) do
		if listing["val"] ~= true then
			currentdir = currentdir + 1
		else
			listing["val"] = false
		end
	end
	
	if con == "up" then
		todir = currentdir - 1
	elseif con == "down" then
		todir = currentdir + 1
	end
	
	print(todir)
	currentmenu[todir]["val"] = true
	cmenu(currentmenu)
end

cmenu(currentmenu)

while true do
	k = key()
	if k ~= "function: 0xb4000078ada06450" then
		move(con)
	end
end

