#!/bin/lua

local mizOS = dofile("mizOS.lua")

local basecommands = {
	["sv"] = mizOS.service,
	["fetch"] = mizOS.software,
	["cc"] = mizOS.software,
	["lspkgs"] = mizOS.software,
	["gfx"] = mizOS.gfx,
	["conf"] = mizOS.config,
	["update"] = mizOS.update,
	["info"] = mizOS.info
}

local arguments = {}
for _,v in pairs(arg) do
	if v ~= "/bin/lua" and v ~= "newmiz" and v ~= "/home/mizosu/Development/mizos/assets/os/testing/newmiz" then
		table.insert(arguments, v)
	end
end


if basecommands[arguments[1]] then
	basecommands[arguments[1]](arguments)
else
	mizOS.root(arguments)
end
