#!/bin/lua
-- [ Made by the Duat. https://entertheduat.org ] --

local argCount = #arg

--[=[ Backend setup ]=]--
local mizOS = dofile("/var/mizOS/core/mizOS.lua")


-- [ Input/Output setup. ] --
local frontend_IO = {}

frontend_IO.inp = function() -- Get user input.
	io.write("\x1b[38;2;137;180;250m> \x1b[38;2;180;190;254m")
	local text = io.read()
	io.write("\x1b[38;2;255;255;255m")
	return text
end
frontend_IO.outp = function(text) -- Write raw output.
	io.write(text)
end
frontend_IO.foutp = function(text) -- Print stylized output.
	print("\x1b[38;2;137;180;250m| \x1b[38;2;180;190;254m" .. text .. "\x1b[38;2;255;255;255m")
end
frontend_IO.afoutp = function(text) -- Print alternate stylized output.
	print("    \x1b[38;2;245;194;231m> \x1b[38;2;203;166;247m" .. text .. "\x1b[38;2;255;255;255m")
end
frontend_IO.err = function(text) -- Print error output.
	print("\x1b[38;2;243;139;168m!![Error]> \x1b[38;2;203;160;247m" .. text .. "\x1b[38;2;255;255;255m")
end

mizOS.initializeIO(frontend_IO)


--[=[ System function handler ]=]--
local function sendInfo()
	mizOS.System.info(arg[2])
end

local function sendConfig()
	mizOS.System.config(arg[2], arg[3])
end

local function sendCsafety()
	if arg[2] then
		mizOS.System.csafety(arg[1], arg[2])
	else
		mizOS.System.csafety(arg[1], nil)
	end
end

local function sendService()
	mizOS.System.service(arg[2], arg[3])
end

local function sendGraphics()
	local value
	if arg[2] == "xd" or arg[2] == "xi" then
		value = {}
		local i = 3
		while i <= argCount do
			table.insert(value, arg[i])
			i = i + 1
		end
	else
		value = arg[3]
	end
	mizOS.System.graphics(arg[2], value)
end

local function sendNetwork()
	if arg[3] then
		mizOS.System.network(arg[2], arg[3])
	else
		mizOS.System.network(arg[2], nil)
	end
end

local function sendSoftware()
	if arg[2] == "cc" then
		mizOS.System.software("clear cache")
		os.exit()
	end
	local packageList = {}
	while argCount > 2 do
		table.insert(packageList, arg[argCount])
		argCount = argCount - 1
	end
	local channelTranslation = {
		["-m"] = "mizos",
		["-p"] = "pacman",
		["-a"] = "aur",
		["-d"] = "desktop"
	}
	mizOS.System.software(arg[1], channelTranslation[arg[2]], packageList)
end

local function sendUpdate()
	local dev = false
	if arg[2] == "dev" then
		dev = true
	end
	mizOS.System.update("system", dev)
	mizOS.System.update("packages", dev)
end


--[=[ Command processor ]=]--
local firstArgSheet = {
	["info"]    = sendInfo,
	["config"]  = sendConfig,
	["backup"]  = sendCsafety,
	["restore"] = sendCsafety,
	["sv"]      = sendService,
	["gfx"]     = sendGraphics,
	["net"]     = sendNetwork,
	["fetch"]   = sendSoftware,
	["remove"]  = sendSoftware,
	["cc"]      = sendSoftware,
	["update"]  = sendUpdate
}

if firstArgSheet[arg[1]] then
	firstArgSheet[arg[1]]()
else
	frontend_IO.err(arg[1] .. " is not a valid \"miz\" command.")
end
