#!/bin/bash


gtk_theme=$(cat /NileRiver/config/$1/gtk/settings/gtk-theme)
icon_theme=$(cat /NileRiver/config/$1/gtk/settings/icon-theme)
cursor_theme=$(cat /NileRiver/config/$1/gtk/settings/cursor-theme)


if [ -f "/NileRiver/config/$1/gtk/settings.ini" ]; then
    rm /NileRiver/config/$1/gtk/settings.ini
fi

cat <<EOF > /NileRiver/config/$1/gtk/settings.ini
[Settings]
gtk-application-prefer-dark-theme=0
gtk-button-images=true
gtk-cursor-theme-name=$cursor_theme
gtk-cursor-theme-size=36
gtk-decoration-layout=:minimize,maximize,close
gtk-enable-animations=true
gtk-font-name=Noto Sans,  10
gtk-icon-theme-name=$icon_theme
gtk-menu-images=true
gtk-modules=colorreload-gtk-module:window-decorations-gtk-module
gtk-primary-button-warps-slider=false
gtk-theme-name=$gtk_theme
gtk-toolbar-style=3
gtk-xft-dpi=98304
EOF